print("What did one wall say to the other wall?")
input("")
print("I'll meet you at the corner!")
input("")
print("{What do you call fake spaghetti?")
input("")
print("An impasta.")
input("")
print("Why can't you trust an atom")
input("")
print("Because they make up everything.")
